# Generated by Django 4.2.7 on 2026-02-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='timeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
